### ISSUE TITLE
ZoneDaemon Performance Issues + Streamable Support

### ISSUE THREAD

**Issue by LuaRook** [EncodedVenom/ZoneDaemon#10]
When using the following code, it seems to generate unwanted performance issues. This could be caused by ``Zone._timer.Tick`` firing at accuracy EPSILON while also checking if the player is within an element or not.  Should we risk delay, or find a way to optimize elements?
```lua
ListenToElementChangesForLocalPlayer:ListenToElementChangesForPlayer("Track", game.Players:GetPlayers()[1]):Connect(function(element)
	print(element)
end)
```

Another issue is incompatibility with ``workspace.StreamingEnabled`` when using ``ZoneDaemon.fromTag``. This can be fixed using sleitnick's Streamable to watch for parts being streamed in and out.

**Comment by EncodedVenom** [comment]
The highest accuracy setting should almost never be used as it fires every heartbeat step. If this issue consistently happens on one of the lower accuracy settings, then it will be an issue.

For example, having a music zone trigger every heartbeat step isn't necessary in my opinion as it doesn't have any real purpose.

StreamingEnabled is an issue but should be split from this issue as it's out of scope of performance issues.
